# Generated by Django 4.2.7 on 2026-02-24 16:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("LOGIN_SUCCESS", "Login Success"),
                            ("LOGIN_FAILED", "Login Failed"),
                            ("LOGOUT", "Logout"),
                            ("TOKEN_REFRESH", "Token Refresh"),
                            ("PASSWORD_CHANGE", "Password Change"),
                            ("PASSWORD_RESET_REQUEST", "Password Reset Request"),
                            ("ACCOUNT_CREATED", "Account Created"),
                            ("ACCOUNT_LOCKED", "Account Locked"),
                            ("ACCOUNT_UNLOCKED", "Account Unlocked"),
                            ("PROFILE_UPDATE", "Profile Update"),
                            ("BOOKING_CREATED", "Booking Created"),
                            ("BOOKING_MODIFIED", "Booking Modified"),
                            ("BOOKING_CANCELLED", "Booking Cancelled"),
                            ("PAYMENT_INITIATED", "Payment Initiated"),
                            ("PAYMENT_SUCCESS", "Payment Success"),
                            ("PAYMENT_FAILED", "Payment Failed"),
                            ("SUSPICIOUS_ACTIVITY", "Suspicious Activity"),
                            ("BRUTE_FORCE_DETECTED", "Brute Force Detected"),
                            ("RATE_LIMIT_EXCEEDED", "Rate Limit Exceeded"),
                            ("UNAUTHORIZED_ACCESS", "Unauthorized Access"),
                            ("SQL_INJECTION_ATTEMPT", "SQL Injection Attempt"),
                            ("XSS_ATTEMPT", "XSS Attempt"),
                            ("ADMIN_LOGIN", "Admin Login"),
                            ("DATA_EXPORT", "Data Export"),
                            ("USER_DELETED", "User Deleted"),
                            ("PERMISSION_CHANGE", "Permission Change"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("INFO", "Info"),
                            ("LOW", "Low"),
                            ("MEDIUM", "Medium"),
                            ("HIGH", "High"),
                            ("CRITICAL", "Critical"),
                        ],
                        default="INFO",
                        max_length=10,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("username_attempted", models.CharField(blank=True, max_length=255)),
                (
                    "ip_address",
                    models.GenericIPAddressField(blank=True, db_index=True, null=True),
                ),
                ("user_agent", models.TextField(blank=True)),
                ("request_method", models.CharField(blank=True, max_length=10)),
                ("request_path", models.CharField(blank=True, max_length=500)),
                ("request_id", models.CharField(blank=True, max_length=36)),
                ("description", models.TextField(blank=True)),
                ("extra_data", models.JSONField(blank=True, default=dict)),
                ("status_code", models.IntegerField(blank=True, null=True)),
                ("session_id", models.CharField(blank=True, max_length=100)),
                ("correlation_id", models.CharField(blank=True, max_length=36)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="BlockedIP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(db_index=True, unique=True),
                ),
                ("reason", models.TextField()),
                ("blocked_at", models.DateTimeField(auto_now_add=True)),
                ("blocked_until", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("auto_blocked", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["-blocked_at"],
            },
        ),
        migrations.CreateModel(
            name="ThreatAlert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "alert_type",
                    models.CharField(
                        choices=[
                            ("BRUTE_FORCE", "Brute Force Attack"),
                            ("CREDENTIAL_STUFFING", "Credential Stuffing"),
                            ("UNUSUAL_LOCATION", "Unusual Login Location"),
                            ("RAPID_BOOKING", "Rapid Booking Pattern"),
                            ("MASS_DATA_ACCESS", "Mass Data Access"),
                            ("AFTER_HOURS_ACCESS", "After Hours Admin Access"),
                            ("MULTIPLE_FAILED_PAYMENTS", "Multiple Failed Payments"),
                            ("ACCOUNT_ENUMERATION", "Account Enumeration"),
                        ],
                        max_length=50,
                    ),
                ),
                ("severity", models.CharField(max_length=10)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPEN", "Open"),
                            ("INVESTIGATING", "Investigating"),
                            ("RESOLVED", "Resolved"),
                            ("FALSE_POSITIVE", "False Positive"),
                        ],
                        default="OPEN",
                        max_length=20,
                    ),
                ),
                ("triggered_at", models.DateTimeField(auto_now_add=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("source_ip", models.GenericIPAddressField(blank=True, null=True)),
                ("description", models.TextField()),
                ("evidence", models.JSONField(default=dict)),
                ("recommended_action", models.TextField(blank=True)),
                (
                    "affected_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "related_logs",
                    models.ManyToManyField(blank=True, to="security.auditlog"),
                ),
            ],
            options={
                "ordering": ["-triggered_at"],
            },
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                fields=["event_type", "timestamp"],
                name="security_au_event_t_13b3b2_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                fields=["ip_address", "timestamp"],
                name="security_au_ip_addr_f227e7_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                fields=["severity", "timestamp"], name="security_au_severit_eb201b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                fields=["user", "timestamp"], name="security_au_user_id_88bbbb_idx"
            ),
        ),
    ]
